### ISSUE TITLE
typing module does not yet have `NoReturn` (py3.6.1)

### ISSUE THREAD

**Issue by reallistic** [colanconnon/apistar_alembic_migrations#1]
When trying to run initialize I get the following error:

```
(venv) chases-iMac:weather chase$ apistar initialize
Traceback (most recent call last):
  File "/Users/chase/workspace/newrelic-weather-challenge/venv/bin/apistar", line 11, in <module>
    load_entry_point('apistar==0.3.9', 'console_scripts', 'apistar')()
  File "/Users/chase/workspace/newrelic-weather-challenge/venv/lib/python3.6/site-packages/apistar/__init__.py", line 31, in main
    app = get_current_app()
  File "/Users/chase/workspace/newrelic-weather-challenge/venv/lib/python3.6/site-packages/apistar/__init__.py", line 46, in get_current_app
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "app.py", line 4, in <module>
    from apistar_alembic_migrations import commands
  File "/Users/chase/workspace/newrelic-weather-challenge/venv/lib/python3.6/site-packages/apistar_alembic_migrations/__init__.py", line 2, in <module>
    from typing import NoReturn, Callable
ImportError: cannot import name 'NoReturn'
```

This was only recently added to the typing library. It would be nice to add < py3.6.2 compatibility (not sure if it landed in .2 or .3).

**Comment by colanconnon** [comment]
Just pushed up a new release (.06) that should resolve this. Let me know if you still see an issue.

**Comment by skillingt** [comment]
Still seeing this issue on Python 3.6.1 with typing version 3.6.6
